/**
 * ITER Analytics Platform - Database Types
 *
 * AUTO-GENERATED by `npm run db:generate-types`
 * DO NOT EDIT MANUALLY
 *
 * Run `npx supabase gen types typescript --local > packages/db/types/database.ts`
 * after any migration change.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type SubscriptionTier = 'free' | 'single_pillar' | 'two_pillar' | 'full' | 'enterprise'
export type PillarType = 'admin' | 'legal' | 'financial'
export type UserRole = 'owner' | 'admin' | 'viewer' | 'iter_admin' | 'iter_super_admin'
export type KpiUnit = 'percentage' | 'currency_brl' | 'days' | 'score' | 'count' | 'ratio'
export type KpiDirection = 'higher_is_better' | 'lower_is_better'
export type AlertSeverity = 'critical' | 'warning' | 'info'
export type AlertStatus = 'active' | 'acknowledged' | 'resolved'
export type DataSource = 'manual' | 'csv_import' | 'erp_sync' | 'diagnostic'

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          cnpj: string
          sector: string | null
          employee_count: number | null
          annual_revenue_range: string | null
          subscription_tier: SubscriptionTier
          active_pillars: PillarType[]
          onboarded_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['organizations']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>
      }
      users: {
        Row: {
          id: string
          auth_id: string
          organization_id: string | null
          role: UserRole
          full_name: string
          email: string
          phone: string | null
          whatsapp_opt_in: boolean
          locale: string
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      kpi_definitions: {
        Row: {
          id: string
          organization_id: string | null
          pillar: PillarType
          name: string
          name_en: string | null
          description: string | null
          unit: KpiUnit
          direction: KpiDirection
          alert_threshold_type: string | null
          alert_threshold_value: number | null
          weight: number
          data_source: DataSource
          is_active: boolean
          display_order: number
          created_at: string
        }
      }
      kpi_data_points: {
        Row: {
          id: string
          kpi_definition_id: string
          organization_id: string
          period_start: string
          period_end: string
          value: number
          source: DataSource
          notes: string | null
          entered_by: string | null
          created_at: string
        }
      }
      alerts: {
        Row: {
          id: string
          organization_id: string
          kpi_definition_id: string
          kpi_data_point_id: string | null
          severity: AlertSeverity
          message: string
          status: AlertStatus
          notified_via: string[]
          notified_at: string | null
          resolved_at: string | null
          resolved_by: string | null
          created_at: string
        }
      }
      diagnostic_reports: {
        Row: {
          id: string
          organization_id: string
          generated_by: string
          questionnaire_response_id: string | null
          admin_score: number | null
          legal_score: number | null
          financial_score: number | null
          overall_score: number | null
          top_risks: Json
          teaser_insights: Json
          full_report_data: Json | null
          pdf_url: string | null
          created_at: string
        }
      }
      questionnaire_responses: {
        Row: {
          id: string
          organization_id: string
          user_id: string
          wizard_version: string
          answers: Json
          pillar_scores_raw: Json | null
          completed_at: string | null
          duration_seconds: number | null
          created_at: string
        }
      }
      ai_chat_sessions: {
        Row: {
          id: string
          organization_id: string
          user_id: string
          title: string | null
          messages: Json
          context_kpis: Json | null
          tokens_used: number
          created_at: string
          updated_at: string
        }
      }
      methodology_documents: {
        Row: {
          id: string
          title: string
          pillar: PillarType | null
          content: string
          metadata: Json | null
          chunk_index: number
          created_at: string
        }
      }
    }
    Functions: {
      calculate_pillar_score: {
        Args: { p_org_id: string; p_pillar: PillarType }
        Returns: number
      }
      calculate_health_score: {
        Args: { p_org_id: string }
        Returns: Json
      }
      match_methodology: {
        Args: {
          query_embedding: number[]
          match_threshold?: number
          match_count?: number
          filter_pillar?: PillarType | null
        }
        Returns: {
          id: string
          title: string
          content: string
          pillar: PillarType | null
          similarity: number
        }[]
      }
    }
  }
}
